create table users(
    username varchar(256) primary key,
    firstname varchar(256) not null,
    lastname varchar(256) not null,
    email varchar(256) not null,
    phone varchar(20) not null,
    address varchar(256) not null,
    password varchar(256) not null,
    imagepath text default 'defaultuser.jpg',
    account numeric default 200000
);
create table admin(
    username varchar(256) primary key,
    firstname varchar(256) not null,
    lastname varchar(256) not null,
    email varchar(256) not null,
    password varchar(256) not null,
    imagepath text default 'defaultadmin.jpg'
);
create table companies (
    id  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(256) not null,
    email varchar(256) not null,  
    phone varchar(256) not null,
    address varchar(256) not null,
    description varchar,
    rating int default 0,
    imagepath text default 'defaultcompany.jpg',
    password varchar(256) not null,
    account numeric default 200000
);

create table comments (
    id  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username references users(username) on delete cascade,
    cid references companies(id) on delete cascade,  
    messages varchar(256) not null,
    placedat varchar(256) not null
);

create table admin (
    username varchar(256) primary key,
    firstname varchar(256) not null,
    lastname varchar(256) not null,
    email varchar(256) not null,
    password varchar(1000) not null,
);
